### ISSUE TITLE
Add `W&B` tracking

### ISSUE THREAD

**Issue by gromdimon** [gromdimon/brain-segment#13]
**Is your feature request related to a problem? Please describe.**
We should use weights and biases for tracking results of model training.

**Describe the solution you'd like**
- [ ] Investigate [Weights and Biases](https://wandb.ai/site)
- [ ] Add setup function in `src/utils.py` for setting up W&B tracking in jupyter notebook
- [ ] Define separate config file for all hyperparameters
- [ ] Research + include all necessary parameters to track (in the created config file)
- [ ] Setup tracking in `notebooks/UNet.ipynb` with help of the created helper function

**Describe alternatives you've considered**
N/A

**Additional context**
Useful links:
Example setup in python: https://docs.wandb.ai/quickstart
Tutorial: https://markjcarlebach.medium.com/getting-started-with-weights-and-biases-19450c33a4ed

**Comment by mathiashusted** [comment]
I've set up an organization for us in W&B. You just need to send me your usernames to add you.

**Comment by evin222** [comment]
evid99 @mathiashusted

**Comment by gromdimon** [comment]
dzhr10

**Comment by mathiashusted** [comment]
@gromdimon Are you sure that's your W&B username? It says it can't find you.

**Comment by gromdimon** [comment]
Ah sorry, i have my classical `gromdimon`

**Comment by gromdimon** [comment]
@mathiashusted could you finish this issue by adding some util function for W&B tracking + creating notebook (or updating existing one) for model training using this utility function?

**Comment by mathiashusted** [comment]
@gromdimon Yes, I'll take care of that as soon as I have a working JupyterLab running. I'll test it ASAP.

**Comment by gromdimon** [comment]
Btw, I've commented the eval step in the original doc, since we should integrate the W&B evaluation there: https://github.com/gromdimon/brain-segment/blob/bfba1d6c8890d6b1d4eec438a21e0da63dc7ef04/src/train.py#L91
